# Generated by Django 3.2.5 on 2021-08-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tasks_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='money',
            field=models.SlugField(),
        ),
    ]
